"use client";
import { useState } from "react";
import { Check, MapPin, ShieldCheck, X } from "lucide-react";
import type { PlaceSuggestion } from "@/lib/admin";
import { Button } from "./ui/Button";

export function AdminPlaceSuggestions({ initialSuggestions }: { initialSuggestions: PlaceSuggestion[] }) {
  const [suggestions, setSuggestions] = useState(initialSuggestions); const [busy, setBusy] = useState<string>(); const [error, setError] = useState("");
  async function review(id: string, action: "approve" | "reject") { setBusy(id); setError(""); try { const response = await fetch(`/api/admin/place-suggestions/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Handlingen mislykkedes."); setSuggestions(current => current.map(item => item.id === id ? { ...item, status: action === "approve" ? "Godkendt" : "Afvist" } : item)); } catch (caught) { setError(caught instanceof Error ? caught.message : "Handlingen mislykkedes."); } finally { setBusy(undefined); } }
  const pending = suggestions.filter(item => item.status === "Afventer");
  return <main className="min-h-screen px-4 pb-28 pt-5 sm:px-6 lg:ml-[238px] lg:px-8 lg:pb-10 xl:px-10"><div className="mx-auto max-w-[960px]"><header><p className="flex items-center gap-2 text-xs font-extrabold uppercase tracking-[.16em] text-clay"><ShieldCheck size={16} />Administration</p><h1 className="mt-2 text-3xl font-extrabold tracking-tight text-ink">Stedforslag</h1><p className="mt-2 text-sm font-semibold text-muted">Gennemgå forslag, før de bliver synlige på stedlisten.</p></header>{error && <p role="alert" className="mt-5 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}<section className="mt-7 space-y-4">{pending.map(item => <article key={item.id} className="rounded-[24px] border border-line bg-limestone p-5 shadow-soft sm:p-6"><div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[.12em] text-moss">{item.type}</p><h2 className="mt-1 text-xl font-extrabold text-ink">{item.name}</h2><p className="mt-2 flex items-start gap-1.5 text-sm font-semibold text-muted"><MapPin size={15} className="mt-0.5" />{item.street}, {item.postalCode} {item.city}</p>{item.note && <p className="mt-3 max-w-xl text-sm leading-6 text-muted">{item.note}</p>}<p className="mt-3 text-xs font-semibold text-muted">Indsendt af {item.submittedBy}</p></div><div className="flex shrink-0 gap-2"><Button variant="outline" disabled={busy === item.id} onClick={() => review(item.id, "reject")}><X size={17} />Afvis</Button><Button disabled={busy === item.id} onClick={() => review(item.id, "approve")}><Check size={17} />Godkend</Button></div></div></article>)}{pending.length === 0 && <div className="rounded-[24px] border border-dashed border-line p-10 text-center"><Check size={26} className="mx-auto text-positive" /><p className="mt-3 text-sm font-extrabold text-ink">Ingen forslag afventer.</p></div>}</section></div></main>;
}
