"use client";
/* eslint-disable @next/next/no-img-element -- Media uses short-lived signed object-storage URLs. */
import Link from "next/link";
import { useState } from "react";
import { Clock3, ImageIcon, MapPin, Play, Target, UserRound } from "lucide-react";
import type { ProjectFeedItem } from "@/types";
import { gymMapForPlace } from "@/lib/gym-maps";
import { ProjectLocationDialog } from "./ProjectLocationDialog";

export function FollowingProjectCard({ item }: { item: ProjectFeedItem }) {
  const { project, media } = item;
  const [mapOpen, setMapOpen] = useState(false);
  const hasMap = Boolean(project.mapPlacement && gymMapForPlace(project.placeSlug));
  return <article className="overflow-hidden rounded-[26px] border border-line bg-limestone shadow-soft"><div className="flex items-center gap-3 p-4 sm:p-5"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-pine text-xs font-extrabold text-limestone">{project.owner?.initials}</span><div className="min-w-0 flex-1"><p data-no-translate className="truncate text-sm font-extrabold">{project.owner?.name}</p><p className="mt-0.5 flex items-center gap-1 text-xs font-semibold text-muted"><UserRound size={12} /><span data-no-translate>@{project.owner?.username}</span> delte et projekt</p></div><span className="rounded-full bg-[#e4eee5] px-3 py-1.5 text-[10px] font-extrabold uppercase tracking-wider text-positive">Offentligt</span></div>
    {media.length > 0 ? <div className={`grid bg-pine ${media.length > 1 ? "grid-cols-2" : ""}`}>{media.map((item, index) => <figure key={item.id} className={`relative overflow-hidden ${media.length === 1 ? "aspect-[4/3]" : "aspect-square"} ${media.length === 3 && index === 0 ? "row-span-2 h-full" : ""}`}>{item.type === "video" ? <><video src={item.url} controls playsInline preload="none" className="h-full w-full object-cover" aria-label={`Video fra ${project.name}`} /><span className="pointer-events-none absolute left-3 top-3 grid h-9 w-9 place-items-center rounded-full bg-limestone/90 text-pine"><Play size={16} fill="currentColor" /></span></> : <img src={item.url} alt={item.note || `Billede fra ${project.name}`} loading="lazy" decoding="async" className="h-full w-full object-cover" />}{item.note && <figcaption data-no-translate className="pointer-events-none absolute inset-x-0 bottom-0 bg-gradient-to-t from-pine/90 to-transparent px-3 pb-12 pt-8 text-xs font-semibold text-limestone">{item.note}</figcaption>}</figure>)}</div> : <div className="grid aspect-[3/1] place-items-center bg-sand text-muted"><span className="flex items-center gap-2 text-xs font-bold"><ImageIcon size={18} />Ingen medier tilføjet endnu</span></div>}
    <div className="p-4 sm:p-5"><div className="flex flex-wrap items-center gap-2 text-xs font-extrabold text-muted"><span className="rounded-full bg-sand px-3 py-1.5 text-clay">{project.grade}</span><span data-no-translate className="flex items-center gap-1"><MapPin size={13} />{project.location}</span><span className="flex items-center gap-1"><Clock3 size={13} />{project.lastAttempt}</span></div><div className="mt-3 flex items-start justify-between gap-4"><div><h3 data-no-translate className="text-xl font-extrabold">{hasMap ? <button type="button" onClick={() => setMapOpen(true)} className="text-left hover:text-clay" aria-label={`Se placering for ${project.name}`}>{project.name}</button> : <Link href={`/projekter/${project.id}`} className="hover:text-clay">{project.name}</Link>}</h3><p className="mt-1 flex items-center gap-1.5 text-xs font-bold text-muted"><Target size={14} />{project.status} · {project.attempts} forsøg</p></div><Link href={`/projekter/${project.id}`} className="shrink-0 rounded-xl bg-pine px-4 py-2.5 text-xs font-extrabold text-limestone">Se projekt</Link></div>{hasMap && <button type="button" onClick={() => setMapOpen(true)} className="mt-4 inline-flex items-center gap-2 rounded-xl border border-line px-4 py-2.5 text-xs font-extrabold text-pine hover:bg-sand"><MapPin size={15} />Se placering på kort</button>}<div className="mt-4 h-1.5 overflow-hidden rounded-full bg-sand"><div className="h-full rounded-full bg-ochre" style={{ width: `${project.progress}%` }} /></div></div>
    {mapOpen && <ProjectLocationDialog project={project} onClose={() => setMapOpen(false)} />}
  </article>;
}
