"use client";
/* eslint-disable @next/next/no-img-element -- Seeded location images are remote URLs managed in Neo4j. */
import Link from "next/link";
import { FormEvent, useMemo, useState } from "react";
import { ArrowRight, CheckCircle2, Clock3, MapPin, Plus, Search, Send, X } from "lucide-react";
import type { ClimbingLocation } from "@/types";
import { Button } from "@/components/ui/Button";

export function LocationsPage({ locations }: { locations: ClimbingLocation[] }) {
  const [query, setQuery] = useState("");
  const [region, setRegion] = useState("Alle");
  const [requestOpen, setRequestOpen] = useState(false);
  const regions = useMemo(() => ["Alle", ...Array.from(new Set(locations.map(location => location.region)))], [locations]);
  const visible = locations.filter(location => (region === "Alle" || location.region === region) && [location.name, location.address, location.region].join(" ").toLowerCase().includes(query.toLowerCase().trim()));
  return <main className="min-h-screen px-4 pb-28 pt-5 sm:px-6 lg:ml-[238px] lg:px-8 lg:pb-10 xl:px-10"><div className="mx-auto max-w-[1220px]">
    <header className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[.16em] text-clay">Find din næste væg</p><h1 className="mt-1 text-3xl font-extrabold tracking-[-.04em] sm:text-4xl">Klatresteder</h1><p className="mt-2 max-w-xl text-sm font-semibold leading-6 text-muted">Find centre, se praktisk information og opdag offentlige projekter fra klatrere i fællesskabet.</p></div><Button onClick={() => setRequestOpen(true)}><Plus size={18} />Foreslå et sted</Button></header>
    <div className="mt-7 grid gap-3 sm:grid-cols-[minmax(0,1fr)_auto]"><label className="relative"><span className="sr-only">Søg efter sted</span><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-muted" size={18} /><input value={query} onChange={event => setQuery(event.target.value)} className="h-12 w-full rounded-2xl border border-line bg-limestone pl-11 pr-4 text-sm font-semibold outline-none focus:border-moss focus:ring-2 focus:ring-moss/20" placeholder="Søg på navn, by eller adresse…" /></label><div className="flex gap-2 overflow-x-auto" aria-label="Filtrér efter region">{regions.map(item => <button key={item} onClick={() => setRegion(item)} aria-pressed={region === item} className={`h-12 shrink-0 rounded-2xl px-4 text-xs font-extrabold ${region === item ? "bg-pine text-limestone" : "border border-line bg-limestone text-muted"}`}>{item}</button>)}</div></div>
    <p className="mt-5 text-xs font-bold text-muted">{visible.length} {visible.length === 1 ? "sted" : "steder"}</p>
    <section className="mt-3 grid gap-4 sm:grid-cols-2 xl:grid-cols-3" aria-label="Klatresteder">{visible.map(location => <Link href={`/klatresteder/${location.id}`} key={location.id} className="group overflow-hidden rounded-[24px] border border-line bg-limestone shadow-soft transition hover:-translate-y-1 hover:border-moss focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-clay"><div className="relative h-48 overflow-hidden bg-pine"><img src={location.imageUrl} alt={location.name} loading="lazy" className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-pine/80 via-transparent to-transparent" /><div className="absolute inset-x-4 bottom-4 text-limestone"><p className="text-[10px] font-extrabold uppercase tracking-[.15em] text-limestone/70">{location.region}</p><h2 className="mt-1 text-xl font-extrabold">{location.name}</h2></div></div><div className="p-4 text-sm font-semibold text-muted"><div className="space-y-3"><p className="flex items-start gap-2"><MapPin size={16} className="mt-0.5 shrink-0 text-clay" />{location.address}</p><p className="flex items-center gap-2"><Clock3 size={16} className="shrink-0 text-clay" />{location.hours} · {location.hoursNote}</p></div><span className="mt-4 flex min-h-11 w-full items-center justify-center gap-2 rounded-2xl bg-pine px-4 text-sm font-extrabold text-limestone transition group-hover:bg-moss">Læs mere <ArrowRight size={17} className="transition group-hover:translate-x-1" /></span></div></Link>)}</section>
    {!visible.length && <div className="mt-4 rounded-[24px] border border-dashed border-line bg-limestone p-10 text-center"><MapPin className="mx-auto text-clay" /><h2 className="mt-3 text-lg font-extrabold">Ingen steder matcher</h2><p className="mt-1 text-sm font-semibold text-muted">Prøv en anden søgning, eller foreslå stedet til os.</p></div>}
  </div>{requestOpen && <LocationRequestModal onClose={() => setRequestOpen(false)} />}</main>;
}

function LocationRequestModal({ onClose }: { onClose: () => void }) {
  const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [sent, setSent] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setLoading(true); setError("");
    try { const response = await fetch("/api/locations/requests", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Forslaget kunne ikke sendes."); setSent(true); }
    catch (caught) { setError(caught instanceof Error ? caught.message : "Forslaget kunne ikke sendes."); } finally { setLoading(false); }
  }
  const field = "mt-2 h-11 w-full rounded-2xl border border-line bg-sand px-4 font-normal outline-none focus:border-moss focus:ring-2 focus:ring-moss/20";
  return <div className="fixed inset-0 z-50 grid place-items-end bg-pine/60 backdrop-blur-sm sm:place-items-center sm:p-5" onMouseDown={event => event.target === event.currentTarget && onClose()}><section role="dialog" aria-modal="true" aria-labelledby="request-title" className="w-full max-w-lg rounded-t-[28px] bg-limestone p-5 shadow-2xl sm:rounded-[28px] sm:p-7"><div className="flex items-start justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[.15em] text-clay">Hjælp fællesskabet</p><h2 id="request-title" className="mt-1 text-2xl font-extrabold">Foreslå et klatrested</h2></div><Button variant="ghost" size="icon" onClick={onClose} aria-label="Luk"><X size={20} /></Button></div>{sent ? <div className="py-10 text-center"><CheckCircle2 size={45} className="mx-auto text-positive" /><h3 className="mt-4 text-xl font-extrabold">Tak for dit forslag!</h3><p className="mt-2 text-sm font-semibold text-muted">Det er sendt til gennemgang og bliver ikke offentliggjort automatisk.</p><Button className="mt-6" onClick={onClose}>Luk</Button></div> : <form onSubmit={submit} className="mt-6 space-y-4"><label className="block text-sm font-extrabold">Navn på stedet<input name="name" required maxLength={100} className={field} placeholder="F.eks. Blocs & Walls" /></label><label className="block text-sm font-extrabold">Adresse<input name="address" required maxLength={180} className={field} placeholder="Gade, postnummer og by" /></label><label className="block text-sm font-extrabold">Website <span className="font-semibold text-muted">(valgfri)</span><input name="website" type="url" maxLength={300} className={field} placeholder="https://…" /></label><label className="block text-sm font-extrabold">Bemærkning <span className="font-semibold text-muted">(valgfri)</span><textarea name="note" maxLength={1000} rows={3} className="mt-2 w-full resize-none rounded-2xl border border-line bg-sand p-4 font-normal outline-none focus:border-moss" placeholder="Fortæl os gerne lidt om stedet" /></label>{error && <p role="alert" className="rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}<Button type="submit" disabled={loading} className="w-full"><Send size={17} />{loading ? "Sender…" : "Send forslag"}</Button></form>}</section></div>;
}
