"use client";
import Link from "next/link";
import Image from "next/image";
import { useMemo, useState } from "react";
import { ArrowRight, Building2, MapPin, Plus, Search } from "lucide-react";
import type { Place } from "@/lib/places";
import { Button } from "./ui/Button";

export function PlacesPage({ places }: { places: Place[] }) {
  const [query, setQuery] = useState("");
  const visible = useMemo(() => { const needle = query.trim().toLocaleLowerCase("da"); return needle ? places.filter(place => `${place.name} ${place.street} ${place.postalCode} ${place.city}`.toLocaleLowerCase("da").includes(needle)) : places; }, [places, query]);
  return <main className="min-h-screen px-4 pb-28 pt-5 sm:px-6 lg:ml-[238px] lg:px-8 lg:pb-10 xl:px-10"><div className="mx-auto max-w-[1120px]"><header className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[.16em] text-clay">Find din næste væg</p><h1 className="mt-1 text-3xl font-extrabold tracking-[-.04em] text-ink sm:text-4xl">Klatresteder</h1><p className="mt-2 max-w-2xl text-sm font-semibold leading-6 text-muted">Find centre, se praktisk information og del steder, der mangler i oversigten.</p></div><Link href="/steder/foreslaa"><Button><Plus size={18} />Foreslå et sted</Button></Link></header><label className="relative mt-7 block"><span className="sr-only">Søg efter sted, by eller adresse</span><Search size={19} className="absolute left-4 top-1/2 -translate-y-1/2 text-muted" /><input value={query} onChange={event => setQuery(event.target.value)} className="h-12 w-full rounded-2xl border border-line bg-limestone pl-12 pr-4 text-sm font-semibold outline-none focus:border-moss focus:ring-2 focus:ring-moss/20" placeholder="Søg efter sted, by eller adresse…" /></label><div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{visible.map(place => <Link key={place.id} href={`/steder/${place.slug}`} className="group overflow-hidden rounded-[24px] border border-line bg-limestone shadow-soft transition hover:-translate-y-0.5 hover:border-moss focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-clay"><div className="relative aspect-[16/8] overflow-hidden bg-pine"><Image src={place.image} alt={place.imageAlt} fill sizes="(max-width: 640px) 100vw, 33vw" className="object-cover transition duration-300 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-pine/30 to-transparent" /></div><div className="p-5"><div className="flex items-start justify-between gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-sand text-clay"><Building2 size={21} /></span><ArrowRight size={19} className="text-muted transition group-hover:translate-x-1 group-hover:text-pine" /></div><h2 className="mt-5 text-lg font-extrabold text-ink">{place.name}</h2><p className="mt-2 flex items-start gap-1.5 text-xs font-semibold leading-5 text-muted"><MapPin size={14} className="mt-0.5 shrink-0" />{place.street}<br />{place.postalCode} {place.city}</p><p className="mt-4 text-xs font-extrabold uppercase tracking-[.12em] text-moss">{place.type}</p></div></Link>)}{visible.length === 0 && <p className="col-span-full rounded-[24px] border border-dashed border-line p-10 text-center text-sm font-semibold text-muted">Ingen steder matcher din søgning.</p>}</div></div></main>;
}
