"use client";
/* eslint-disable @next/next/no-img-element -- signed object-storage URLs are dynamic. */
import { ChangeEvent, FormEvent, useEffect, useState } from "react";
import { Camera, Upload, Video, X } from "lucide-react";
import type { ClimbingProject, ProjectMedia } from "@/types";
import { Button } from "./ui/Button";

export function ProjectMediaPanel({ projectId, version = 0 }: { projectId: string; version?: number }) {
  const [media, setMedia] = useState<ProjectMedia[]>([]);
  useEffect(() => { fetch(`/api/projects/${projectId}/media`).then(response => response.ok ? response.json() : { media: [] }).then(result => setMedia(Array.isArray(result.media) ? result.media : [])).catch(() => setMedia([])); }, [projectId, version]);
  if (!media.length) return null;
  return <section className="mt-4 rounded-[24px] border border-line bg-limestone p-5 shadow-soft" aria-labelledby="uploaded-media-title"><h2 id="uploaded-media-title" className="text-xl font-extrabold">Delte billeder og videoer</h2><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3">{media.map(item => <figure key={item.id} className="overflow-hidden rounded-2xl bg-sand">{item.type === "video" ? <video src={item.url} controls playsInline preload="none" className="aspect-square w-full object-cover" aria-label={item.note || "Video fra projektet"} /> : <img src={item.url} alt={item.note || "Billede fra projektet"} loading="lazy" decoding="async" className="aspect-square w-full object-cover" />}{item.note && <figcaption className="p-3 text-xs font-semibold text-muted">{item.note}</figcaption>}</figure>)}</div></section>;
}

export function MediaUploadModal({ project, onClose, onSaved }: { project: ClimbingProject; onClose: () => void; onSaved: () => void }) {
  const [files, setFiles] = useState<File[]>([]); const [note, setNote] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  function addFiles(event: ChangeEvent<HTMLInputElement>) { if (event.target.files) setFiles(Array.from(event.target.files)); }
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(""); try { for (const file of files) { const prepare = await fetch(`/api/projects/${project.id}/media`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "prepare", contentType: file.type, size: file.size }) }); const prepared = await prepare.json(); if (!prepare.ok) throw new Error(prepared.error); const upload = await fetch(prepared.uploadUrl, { method: "PUT", headers: { "Content-Type": file.type }, body: file }); if (!upload.ok) throw new Error("Filen kunne ikke uploades."); const complete = await fetch(`/api/projects/${project.id}/media`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "complete", key: prepared.key, contentType: file.type, size: file.size, note }) }); const completed = await complete.json(); if (!complete.ok) throw new Error(completed.error); } onSaved(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Mediet kunne ikke gemmes."); } finally { setLoading(false); } }
  return <div className="fixed inset-0 z-50 grid place-items-end bg-pine/60 backdrop-blur-sm sm:place-items-center sm:p-5" onMouseDown={event => event.target === event.currentTarget && onClose()}><section role="dialog" aria-modal="true" aria-labelledby="media-upload-title" className="w-full max-w-xl rounded-t-[28px] bg-limestone p-5 shadow-2xl sm:rounded-[28px] sm:p-7"><div className="flex items-start justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[.15em] text-clay">{project.name}</p><h2 id="media-upload-title" className="mt-1 text-2xl font-extrabold">Nyt forsøg</h2></div><Button variant="ghost" size="icon" onClick={onClose} aria-label="Luk"><X size={20} /></Button></div><form onSubmit={submit}><div className="mt-5 grid grid-cols-2 gap-3"><label className="flex min-h-24 cursor-pointer flex-col items-center justify-center gap-2 rounded-[20px] border border-dashed border-moss bg-sand text-sm font-extrabold"><Camera size={22} />Billede<input type="file" accept="image/jpeg,image/png,image/webp" onChange={addFiles} className="sr-only" aria-label="Vælg billede" /></label><label className="flex min-h-24 cursor-pointer flex-col items-center justify-center gap-2 rounded-[20px] border border-dashed border-moss bg-sand text-sm font-extrabold"><Video size={22} />Video<input type="file" accept="video/mp4,video/webm" onChange={addFiles} className="sr-only" aria-label="Vælg video" /></label></div>{files.length > 0 && <p className="mt-3 text-sm font-bold text-positive">{files.map(file => file.name).join(", ")}</p>}<label className="mt-4 block text-sm font-extrabold">Note <span className="font-semibold text-muted">(valgfri)</span><textarea value={note} onChange={event => setNote(event.target.value)} rows={3} className="mt-2 w-full rounded-2xl border border-line bg-sand p-4 font-normal" /></label>{error && <p role="alert" className="mt-3 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}<Button type="submit" disabled={loading || !files.length} className="mt-5 w-full"><Upload size={17} />{loading ? "Uploader…" : "Gem forsøg"}</Button></form></section></div>;
}
