"use client";
import { FormEvent, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Check, Send } from "lucide-react";
import { Button } from "./ui/Button";

export function SuggestPlaceForm() {
  const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [sent, setSent] = useState(false);
  const inputClass = "mt-2 h-11 w-full rounded-2xl border border-line bg-sand px-4 font-normal outline-none focus:border-moss focus:ring-2 focus:ring-moss/20";
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(""); try { const response = await fetch("/api/places/suggestions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Forslaget kunne ikke sendes."); setSent(true); } catch (caught) { setError(caught instanceof Error ? caught.message : "Forslaget kunne ikke sendes."); } finally { setLoading(false); } }
  return <main className="min-h-screen px-4 pb-28 pt-5 sm:px-6 lg:ml-[238px] lg:px-8 lg:pb-10 xl:px-10"><div className="mx-auto max-w-[680px]"><Link href="/steder" className="inline-flex items-center gap-2 text-sm font-extrabold text-muted hover:text-ink"><ArrowLeft size={17} />Alle steder</Link><section className="mt-5 rounded-[28px] border border-line bg-limestone p-5 shadow-soft sm:p-8"><p className="text-xs font-extrabold uppercase tracking-[.15em] text-clay">Hjælp fællesskabet</p><h1 className="mt-1 text-3xl font-extrabold tracking-tight text-ink">Foreslå et nyt sted</h1><p className="mt-3 text-sm font-semibold leading-6 text-muted">Kender du et klatrecenter eller et andet klatrested, der mangler? Send oplysningerne, så kan det blive gennemgået, før det kommer på listen.</p>{sent ? <div className="mt-7 rounded-[22px] bg-[#e4eee5] p-6 text-center"><Check size={28} className="mx-auto text-positive" /><h2 className="mt-3 text-xl font-extrabold text-ink">Tak for dit forslag</h2><p className="mt-2 text-sm font-semibold text-muted">Det er gemt og klar til gennemgang.</p><Link href="/steder" className="mt-5 inline-flex"><Button>Tilbage til steder</Button></Link></div> : <form onSubmit={submit} className="mt-7 space-y-4"><label className="block text-sm font-extrabold">Stedets navn<input name="name" required className={inputClass} placeholder="F.eks. Klippehallen" /></label><label className="block text-sm font-extrabold">Adresse<input name="street" required className={inputClass} placeholder="Gade og nummer" /></label><div className="grid gap-4 sm:grid-cols-[140px_1fr]"><label className="block text-sm font-extrabold">Postnummer<input name="postalCode" required inputMode="numeric" className={inputClass} placeholder="2200" /></label><label className="block text-sm font-extrabold">By<input name="city" required className={inputClass} placeholder="København" /></label></div><label className="block text-sm font-extrabold">Type<select name="type" className={inputClass}><option>Bouldering</option><option>Rebklatring</option><option>Udendørs</option><option>Andet</option></select></label><label className="block text-sm font-extrabold">Praktisk info eller link <span className="font-semibold text-muted">(valgfrit)</span><textarea name="note" rows={4} className="mt-2 w-full resize-none rounded-2xl border border-line bg-sand p-4 font-normal outline-none focus:border-moss focus:ring-2 focus:ring-moss/20" placeholder="Hjemmeside, faciliteter eller andet vi bør vide…" /></label>{error && <p role="alert" className="rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}<Button type="submit" disabled={loading} className="w-full"><Send size={17} />{loading ? "Sender…" : "Send forslag"}</Button></form>}</section></div></main>;
}
