import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { cookies } from "next/headers";
import { notFound, redirect } from "next/navigation";
import { ArrowLeft, Clock3, ExternalLink, Info, MapPin, Mountain } from "lucide-react";
import { SESSION_COOKIE, userFromSession } from "@/lib/auth";
import { mapUrl, places } from "@/lib/places";
import { getPlaceBySlug } from "@/lib/place-data";
import { Button } from "@/components/ui/Button";

export function generateStaticParams() { return places.map(place => ({ slug: place.slug })); }
export async function generateMetadata({ params }: { params: { slug: string } }): Promise<Metadata> { const place = await getPlaceBySlug(params.slug); return { title: place ? `${place.name} · Boulde` : "Sted ikke fundet · Boulde" }; }
export default async function PlaceDetail({ params }: { params: { slug: string } }) {
  if (!await userFromSession(cookies().get(SESSION_COOKIE)?.value)) redirect("/login");
  const place = await getPlaceBySlug(params.slug); if (!place) notFound();
  return <main className="min-h-screen px-4 pb-28 pt-5 sm:px-6 lg:ml-[238px] lg:px-8 lg:pb-10 xl:px-10"><div className="mx-auto max-w-[900px]"><Link href="/steder" className="inline-flex items-center gap-2 text-sm font-extrabold text-muted hover:text-ink"><ArrowLeft size={17} />Alle steder</Link><section className="mt-5 overflow-hidden rounded-[28px] border border-line bg-limestone shadow-soft"><div className="relative overflow-hidden bg-pine p-6 text-limestone sm:p-9"><Image src={place.image} alt={place.imageAlt} fill priority className="object-cover opacity-35" /><div className="absolute inset-0 bg-gradient-to-r from-pine via-pine/80 to-pine/30" /><div className="relative"><span className="grid h-14 w-14 place-items-center rounded-[20px] bg-limestone/10"><Mountain size={27} /></span><p className="mt-6 text-xs font-extrabold uppercase tracking-[.15em] text-[#cbd5c9]">{place.type}</p><h1 className="mt-1 text-3xl font-extrabold tracking-tight sm:text-4xl">{place.name}</h1><p className="mt-3 flex items-start gap-2 text-sm font-semibold text-[#d9dfd7]"><MapPin size={17} className="mt-0.5" />{place.street}, {place.postalCode} {place.city}</p></div></div><div className="grid gap-5 p-5 sm:grid-cols-2 sm:p-8"><article className="rounded-[22px] bg-sand p-5"><MapPin size={21} className="text-clay" /><h2 className="mt-4 text-lg font-extrabold text-ink">Adresse og vej</h2><p className="mt-2 text-sm font-semibold leading-6 text-muted">{place.street}<br />{place.postalCode} {place.city}</p><a href={mapUrl(place)} target="_blank" rel="noreferrer" className="mt-4 inline-flex"><Button size="sm">Åbn i kort <ExternalLink size={15} /></Button></a></article><article className="rounded-[22px] bg-sand p-5"><Clock3 size={21} className="text-clay" /><h2 className="mt-4 text-lg font-extrabold text-ink">Før dit besøg</h2><p className="mt-2 text-sm font-semibold leading-6 text-muted">Tjek stedets egne kanaler for aktuelle åbningstider, priser, hold og særlige adgangsforhold.</p></article><article className="rounded-[22px] border border-line p-5 sm:col-span-2"><Info size={21} className="text-moss" /><h2 className="mt-4 text-lg font-extrabold text-ink">Praktisk information</h2><p className="mt-2 text-sm font-semibold leading-6 text-muted">Dette er en ny stedside. Flere oplysninger om faciliteter, udlejning, parkering og tilgængelighed kan tilføjes, når de er verificeret.</p><Link href="/steder/foreslaa" className="mt-4 inline-flex text-sm font-extrabold text-clay hover:text-ink">Har du en rettelse eller mere information? Send den til os →</Link></article></div></section></div></main>;
}
